// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package repositories

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeadLetter struct {
	ScheduleID uuid.UUID          `json:"schedule_id"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ModelSchedule struct {
	ModelName string             `json:"model_name"`
	LastRun   pgtype.Timestamptz `json:"last_run"`
}

type WorkSchedule struct {
	ScheduleID uuid.UUID          `json:"schedule_id"`
	WorkerID   uuid.UUID          `json:"worker_id"`
	StartRun   pgtype.Timestamptz `json:"start_run"`
	EndRun     pgtype.Timestamptz `json:"end_run"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	State      string             `json:"state"`
}

type WorkerRegister struct {
	WorkerID  uuid.UUID          `json:"worker_id"`
	Capacity  int32              `json:"capacity"`
	HeartBeat pgtype.Timestamptz `json:"heart_beat"`
}
