// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package repositories

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Archive(ctx context.Context, scheduleID uuid.UUID) error
	GetCurrentQueueSize(ctx context.Context, workerID uuid.UUID) (int64, error)
	GetNext(ctx context.Context, workerID uuid.UUID) (*WorkSchedule, error)
	InsertQueueItem(ctx context.Context, arg *InsertQueueItemParams) error
	Ping(ctx context.Context) (int32, error)
	StartProcessing(ctx context.Context, scheduleID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
