// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package repositories

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	InsertDeadLetter(ctx context.Context, scheduleID uuid.UUID) error
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
