// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: queries.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
)

const insertDeadLetter = `-- name: InsertDeadLetter :exec
INSERT INTO dead_letter
    (
        schedule_id
    )
VALUES
    (
        $1
    )
`

func (q *Queries) InsertDeadLetter(ctx context.Context, scheduleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertDeadLetter, scheduleID)
	return err
}

const ping = `-- name: Ping :one
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
