// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package repositories

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetLast(ctx context.Context, modelName string) (pgtype.Timestamptz, error)
	Ping(ctx context.Context) (int32, error)
	UpsertModel(ctx context.Context, arg *UpsertModelParams) error
}

var _ Querier = (*Queries)(nil)
