// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package repositories

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type WorkerRegister struct {
	WorkerID  uuid.UUID          `json:"worker_id"`
	HeartBeat pgtype.Timestamptz `json:"heart_beat"`
}
