// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package repositories

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeregisterWorker(ctx context.Context, workerID uuid.UUID) error
	GetWorkers(ctx context.Context) ([]*GetWorkersRow, error)
	Ping(ctx context.Context) (int32, error)
	RegisterWorker(ctx context.Context, arg *RegisterWorkerParams) error
	UpdateWorkerHeartbeat(ctx context.Context, workerID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
