// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: queries.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
)

const ping = `-- name: Ping :one
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const registerWorker = `-- name: RegisterWorker :exec
INSERT INTO worker_register (worker_id)
VALUES (
    $1
)
`

func (q *Queries) RegisterWorker(ctx context.Context, workerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, registerWorker, workerID)
	return err
}

const updateWorkerHeartbeat = `-- name: UpdateWorkerHeartbeat :exec
UPDATE worker_register
SET
    heart_beat = now()
WHERE
    worker_id = $1
`

func (q *Queries) UpdateWorkerHeartbeat(ctx context.Context, workerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateWorkerHeartbeat, workerID)
	return err
}
