name: orbis

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: orbis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: orbis
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
